### ISSUE TITLE
Auto GG does not work on Galaxite

### ISSUE THREAD

**Issue by ThatJadon26** [HugoNotHere/OnixClientFaq#3]
When a game is over, the auto GG does not type gg in chat.

https://user-images.githubusercontent.com/69434809/132165940-a60f7306-76c5-48e6-b311-2dc1d7bea90e.mp4

**Comment by HugoNotHere** [comment]
Hey, sorry for the late response, please can you check if your game language is English as it needs to be for auto gg to work.

**Comment by HugoNotHere** [comment]
hey, sorry, but onix never even added auto gg to galaxite ;-;
And I don't think he is planning to. Sorry about that.

**Comment by ThatJadon26** [comment]
> hey, sorry, but onix never even added auto gg to galaxite ;-;
> And I don't think he is planning to. Sorry about that.

I’m sure he never did, but the point of auto GG is to say gg automatically in chat for any game. That wouldn’t make sense not to add it to galaxite and any other server it doesn’t work with atm. It’s annoying to have to say it manually after ever game to get xp
