### ISSUE TITLE
This isn't really an issue, more of a suggestion.

### ISSUE THREAD

**Issue by notJudahRR** [HugoNotHere/OnixClientFaq#32]
I think we should make a Onix Client organization which I can organize for everyone, we will invite Onix, and we can move the FAQ there. I'll maintain it with Onix, Hugo, and if Carlton joins him too. I think that would be better for everyone. I will give everyone an owner role. What do you think?

**Comment by notJudahRR** [comment]
https://github.com/OnixClientMC here is the link

**Comment by HugoNotHere** [comment]
what's better having it that way then it was before?

**Comment by notJudahRR** [comment]
Well, it will be more centralized as I plan on getting the launcher source code there, and other projects, instead of having to go to many repositories. For example, to get the launcher code, you must go to carlton's Github page. However, to get the FAQ, you must go to this Github page. With the Onix Client organization, it will all be together, and easy to use.

**Comment by HugoNotHere** [comment]
you will need to get Carlton's permission for that one.
